server:
  port: 9030

spring:
  profiles:
    active: local

  application:
    name: user-service-api
    description: "SpringBoot JPA H2 Redis JWT Security User Service Api"

  jackson:
    time-zone: "Asia/Seoul"

  datasource:
    driverClassName: org.h2.Driver
#    jdbcUrl: jdbc:h2:file:~/h2db/test;MODE=MySql
    jdbcUrl: jdbc:h2:mem:test;MODE=MySql

    username: sa
    password:
    maximumPoolSize: 30
    minimumIdle: 5
    poolName: dbrenzo
    readOnly: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: fase
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      enabled: true

  redis:
    host: localhost
    port: 6379